### ISSUE TITLE
Exception: Drummer cannot be bound to two band handles at once

### ISSUE THREAD

**Issue by szymon-rd** [kgadek/miss-understanding#1]
I tried to bind the band's drummer instance to a second band handle. He threw an exception at me. Is that expected behaviour? 

@kgadek Please address this issue as its blocking workflow of my team

**Comment by kgadek** [comment]
[Fix your](https://youtu.be/v_QEZsJtt9w?feature=shared&t=38) [workflow](https://xkcd.com/1172/)
